### ISSUE TITLE
Looks ideal but

### ISSUE THREAD

**Issue by ftrotter** [guidone/Restizr#1]
guidone,
           This module looks ideal for us, but there are couple of things that are unclear on the first read of how the app works...

First, your example has (apparently?) psuedo code for how your code integrates with Express. That's a little confusing since I (and other hopeful users I imagine) are trying to sort out how to use Express effectively at the same time as your module. 

Much better would be a sample app (bookstore or other classic basic app) that shows how MySQL table -> Sequelize -> your stuff + express -> a REST interface... 

Also, it is not clear what you actually send to the REST interface... are you sending and receiving JSON.. for instance... How do you handle the linking of Sequelize objects? (i.e. if you create a new book using REST how do you link that object over to a 'Author' object...)

I know these are pretty high-level complaints, and I know that the answers are all in your sourcecode somewhere... but if your hope to have your module adopted "off the shelf" these questions need clear and unambigous answers...

Thanks,
-FT

**Comment by massimiliano-della-rovere** [comment]
ftrotter, it's a bit late, but maybe it can be useful to others.

Here is an example of integration with Express Router.

<pre>
var express = require('express');
var router = express.Router();
/* GET home page. */
router.get('/', function(req, res, next) {
  // do something with res :)
});
var
  Sequelize = require("sequelize"),
  sequelize = new Sequelize(
    "database_prova",
    "username",
    "password",
    {
      dialect: "sqlite",
      storage: "demo_db.sqlite"
    }
  );
sequelize
  .authenticate()
  .complete(function(err) {
    if (err) {
      console.error("Cannot connect to DB");
      // process.exit(1);
    } else {
      console.log("Connected to DB!");
    }
  });
var MyObject = sequelize.define(
  "MyObject",
  {
    name: Sequelize.STRING(50),
    surname: Sequelize.STRING(50),
    born: Sequelize.DATE,
    age: Sequelize.INTEGER.UNSIGNED,
    bool: Sequelize.BOOLEAN
  },
  {
    getterMethods: {
      fullName: function() {
        return this.name + " " + this.surname;
      }
    },
    setterMethods: {
      fullName: function(value) {
        var names = value.split(" ");
        this.setDataValue("name", names.slice(0, -1).join(" "));
        this.setDataValue("surname", names.slice(-1).join(" "));
      }
    }
  });
var Restizr = require("restizr");
var rest = new Restizr(router);
rest.map(MyObject);
module.exports = router;
</pre>

In the index.js of restizr, find the exported "map" function: you have to replace the key "del" with "delete".

In the next few days, I hope I'll have the time to commit a new version that:
1) plays nicely with Express 4 (usage of req.params, req,body and req.query instead of req.param);
2) returns HTTP 404 when a resource is not found (GET :id, PUT :id and DELETE :id).
